const electricalSystemsBilingualResources = freezeResources({
    "visible-thermal-stress-indication": {
        cause: { en: "visible thermal stress or overheating indicators", de: "sichtbare Hinweise auf thermische Beanspruchung oder Überhitzung" },
        label: { en: "visible thermal stress or overheating indicators", de: "sichtbare Hinweise auf thermische Beanspruchung oder Überhitzung" },
        classification: { en: "visual electrical hypothesis", de: "visuelle Elektrohypothese" },
        supportingIndicators: { en: ["visible discoloration or scorching is reported at an electrical component", "overheating-related marks may be associated with prior thermal stress", "visual inspection alone is insufficient to confirm the technical cause"], de: ["sichtbare Verfärbung oder Schmorspuren werden an einer Elektrokomponente berichtet", "überhitzungsbezogene Spuren können mit früherer thermischer Beanspruchung zusammenhängen", "die Sichtprüfung allein reicht nicht aus, um die technische Ursache zu bestätigen"] },
        contradictingIndicators: { en: ["marks are confirmed to be unrelated surface contamination", "component is tested and assessed by a qualified electrical specialist without abnormal thermal indication"], de: ["Spuren werden als unabhängige Oberflächenverunreinigung bestätigt", "die Komponente wird durch eine qualifizierte Elektrofachkraft ohne auffällige thermische Hinweise geprüft"] },
        requiredVerification: { en: ["Document the affected component and location.", "Further electrical inspection may be appropriate before assigning cause.", "Condition cannot be confirmed without testing by a qualified electrical specialist."], de: ["Betroffene Komponente und Lage dokumentieren.", "Vor einer Ursachenzuordnung kann eine weiterführende Elektroprüfung angemessen sein.", "Der Zustand kann ohne Prüfung durch eine qualifizierte Elektrofachkraft nicht bestätigt werden."] },
        potentialConsequences: { en: ["increased need for specialist review", "possible deterioration of affected component", "potential interruption of electrical service if the condition progresses"], de: ["erhöhter Bedarf an fachlicher Prüfung", "mögliche Verschlechterung der betroffenen Komponente", "mögliche Unterbrechung der Stromversorgung bei Fortschreiten des Zustands"] },
        recommendedActions: { en: ["Record visible marks without inferring confirmed overheating.", "Keep the finding within visual-inspection limits.", "Request qualified electrical assessment where thermal marks remain unexplained."], de: ["Sichtbare Spuren erfassen, ohne bestätigte Überhitzung abzuleiten.", "Die Feststellung auf die Grenzen der Sichtprüfung beschränken.", "Bei ungeklärten thermischen Spuren qualifizierte Elektroprüfung veranlassen."] }
    },
    "damaged-or-incomplete-electrical-enclosure": {
        cause: { en: "damaged or incomplete electrical enclosure", de: "beschädigtes oder unvollständiges Elektrogehäuse" },
        label: { en: "damaged or incomplete electrical enclosure", de: "beschädigtes oder unvollständiges Elektrogehäuse" },
        classification: { en: "visual electrical hypothesis", de: "visuelle Elektrohypothese" },
        supportingIndicators: { en: ["cover or enclosure condition is visibly incomplete or damaged", "enclosure condition may reduce protection of internal components", "direct functional relevance requires electrical verification"], de: ["Abdeckung oder Gehäusezustand erscheint sichtbar unvollständig oder beschädigt", "der Gehäusezustand kann den Schutz innerer Komponenten verringern", "die unmittelbare Funktionsrelevanz erfordert elektrotechnische Verifikation"] },
        contradictingIndicators: { en: ["cover is intact and correctly secured", "reported damage is unrelated to electrical equipment"], de: ["die Abdeckung ist intakt und korrekt befestigt", "der berichtete Schaden steht nicht mit elektrischer Ausrüstung in Zusammenhang"] },
        requiredVerification: { en: ["Inspect the visible cover, enclosure, and accessible fixings.", "Verify whether internal components remain protected without touching live parts.", "Further electrical inspection may be appropriate before defining repair scope."], de: ["Sichtbare Abdeckung, Gehäuse und zugängliche Befestigungen prüfen.", "Ohne Berührung spannungsführender Teile prüfen, ob innere Komponenten geschützt bleiben.", "Vor Festlegung des Umfangs kann weitere Elektroprüfung angemessen sein."] },
        potentialConsequences: { en: ["reduced component protection", "increased maintenance demand", "possible exposure of internal equipment to dust or impact"], de: ["verminderter Komponentenschutz", "erhöhter Instandhaltungsbedarf", "mögliche Einwirkung von Staub oder Stoß auf interne Ausrüstung"] },
        recommendedActions: { en: ["Document the enclosure and missing or damaged cover condition.", "Avoid opening or manipulating energized equipment during visual review.", "Request qualified electrical follow-up where protection appears incomplete."], de: ["Gehäusezustand und fehlende oder beschädigte Abdeckung dokumentieren.", "Während der Sichtprüfung kein unter Spannung stehendes Gerät öffnen oder manipulieren.", "Bei unvollständig erscheinendem Schutz qualifizierte Elektroprüfung veranlassen."] }
    },
    "exposed-or-insufficiently-protected-conductors": {
        cause: { en: "exposed or insufficiently protected conductors", de: "freiliegende oder unzureichend geschützte Leiter" },
        label: { en: "exposed or insufficiently protected conductors", de: "freiliegende oder unzureichend geschützte Leiter" },
        classification: { en: "visual electrical hypothesis", de: "visuelle Elektrohypothese" },
        supportingIndicators: { en: ["visible conductor exposure or insulation damage is reported", "conductor protection may be incomplete", "condition cannot be confirmed without testing and safe access"], de: ["sichtbar freiliegende Leiter oder Isolationsschäden werden berichtet", "der Leiterschutz kann unvollständig sein", "der Zustand kann ohne Prüfung und sicheren Zugang nicht bestätigt werden"] },
        contradictingIndicators: { en: ["conductors are enclosed and insulation appears intact", "visible item is not part of the electrical installation"], de: ["Leiter sind eingeschlossen und die Isolierung erscheint intakt", "das sichtbare Bauteil gehört nicht zur Elektroinstallation"] },
        requiredVerification: { en: ["Do not touch exposed or uncertain conductors during visual inspection.", "Document the location and extent of visible exposure.", "Qualified electrical inspection may be appropriate before use or intervention decisions."], de: ["Freiliegende oder unklare Leiter während der Sichtprüfung nicht berühren.", "Lage und Umfang der sichtbaren Freilegung dokumentieren.", "Vor Nutzungs- oder Eingriffsentscheidungen kann qualifizierte Elektroprüfung angemessen sein."] },
        potentialConsequences: { en: ["increased need for immediate specialist review", "possible service interruption until assessed", "restricted safe access to the affected area"], de: ["erhöhter Bedarf an unmittelbarer fachlicher Prüfung", "mögliche Nutzungsunterbrechung bis zur Bewertung", "eingeschränkter sicherer Zugang zum betroffenen Bereich"] },
        recommendedActions: { en: ["Record the visible condition and access context.", "Keep conclusions limited to visible conductor protection.", "Escalate for qualified electrical assessment where exposure is observed."], de: ["Sichtbaren Zustand und Zugangssituation erfassen.", "Schlussfolgerungen auf den sichtbaren Leiterschutz beschränken.", "Bei beobachteter Freilegung qualifizierte Elektroprüfung veranlassen."] }
    },
    "moisture-or-corrosion-related-electrical-deterioration": {
        cause: { en: "visible corrosion or moisture-related electrical deterioration", de: "sichtbare Korrosion oder feuchtebezogene elektrische Verschlechterung" },
        label: { en: "visible corrosion or moisture-related electrical deterioration", de: "sichtbare Korrosion oder feuchtebezogene elektrische Verschlechterung" },
        classification: { en: "visual electrical hypothesis", de: "visuelle Elektrohypothese" },
        supportingIndicators: { en: ["corrosion or moisture proximity is reported near electrical equipment", "visible deterioration may be associated with environmental exposure", "electrical condition requires verification beyond visual observation"], de: ["Korrosion oder Feuchtenähe wird nahe elektrischer Ausrüstung berichtet", "sichtbare Verschlechterung kann mit Umwelteinwirkung zusammenhängen", "der elektrische Zustand erfordert Verifikation über die Sichtbeobachtung hinaus"] },
        contradictingIndicators: { en: ["corrosion is superficial and unrelated to electrical components", "moisture source is confirmed absent after specialist assessment"], de: ["Korrosion ist oberflächlich und steht nicht mit elektrischen Komponenten in Zusammenhang", "eine Feuchtequelle wird nach fachlicher Prüfung als nicht vorhanden bestätigt"] },
        requiredVerification: { en: ["Document corrosion, staining, or moisture proximity with location context.", "Identify visible moisture source indicators without inferring electrical failure.", "Further electrical inspection may be appropriate where moisture and electrical equipment are adjacent."], de: ["Korrosion, Verfärbung oder Feuchtenähe mit Lagebezug dokumentieren.", "Sichtbare Hinweise auf Feuchtequellen erfassen, ohne elektrisches Versagen abzuleiten.", "Bei Nähe von Feuchte und elektrischer Ausrüstung kann weitere Elektroprüfung angemessen sein."] },
        potentialConsequences: { en: ["accelerated component deterioration", "increased maintenance demand", "possible interruption of affected electrical equipment"], de: ["beschleunigte Komponentenverschlechterung", "erhöhter Instandhaltungsbedarf", "mögliche Unterbrechung betroffener elektrischer Ausrüstung"] },
        recommendedActions: { en: ["Record the visible relationship between moisture and electrical components.", "Avoid attributing internal failure from moisture proximity alone.", "Coordinate moisture-source review and qualified electrical assessment where relevant."], de: ["Sichtbaren Zusammenhang zwischen Feuchte und elektrischen Komponenten erfassen.", "Aus Feuchtenähe allein kein internes Versagen ableiten.", "Bei Relevanz Feuchtequellenprüfung und qualifizierte Elektroprüfung koordinieren."] }
    },
    "temporary-or-poorly-supported-wiring": {
        cause: { en: "temporary or poorly supported wiring", de: "provisorische oder unzureichend befestigte Verdrahtung" },
        label: { en: "temporary or poorly supported wiring", de: "provisorische oder unzureichend befestigte Verdrahtung" },
        classification: { en: "visual electrical hypothesis", de: "visuelle Elektrohypothese" },
        supportingIndicators: { en: ["wiring or cable support appears temporary or incomplete", "poor cable support may affect durability or protection", "installation intent cannot be confirmed from visual inspection alone"], de: ["Verdrahtung oder Kabelbefestigung erscheint provisorisch oder unvollständig", "unzureichende Kabelbefestigung kann Dauerhaftigkeit oder Schutz beeinflussen", "die Installationsabsicht kann aus der Sichtprüfung allein nicht bestätigt werden"] },
        contradictingIndicators: { en: ["cables are permanently fixed and adequately supported", "reported temporary item is not part of the building electrical installation"], de: ["Kabel sind dauerhaft befestigt und ausreichend unterstützt", "das berichtete Provisorium gehört nicht zur Gebäudeelektroinstallation"] },
        requiredVerification: { en: ["Document cable route, support condition, and apparent temporary arrangement.", "Verify installation intent and documentation where available.", "Further electrical inspection may be appropriate before classifying the arrangement."], de: ["Kabelverlauf, Befestigungszustand und offenbar provisorische Anordnung dokumentieren.", "Installationsabsicht und Dokumentation prüfen, soweit verfügbar.", "Vor Einstufung der Anordnung kann weitere Elektroprüfung angemessen sein."] },
        potentialConsequences: { en: ["increased maintenance demand", "possible mechanical damage to cable runs", "reduced reliability of the visible arrangement"], de: ["erhöhter Instandhaltungsbedarf", "mögliche mechanische Schäden an Leitungswegen", "verminderte Zuverlässigkeit der sichtbaren Anordnung"] },
        recommendedActions: { en: ["Record visible cable support irregularities.", "Do not infer installation non-compliance from appearance alone.", "Request qualified review if temporary wiring appears to serve building use."], de: ["Sichtbare Unregelmäßigkeiten der Kabelbefestigung erfassen.", "Aus dem Erscheinungsbild allein keine Regelwidrigkeit ableiten.", "Qualifizierte Prüfung veranlassen, wenn provisorische Verdrahtung der Gebäudenutzung zu dienen scheint."] }
    },
    "damaged-socket-or-switch-component": {
        cause: { en: "damaged socket or switch component", de: "beschädigte Steckdose oder beschädigter Schalter" },
        label: { en: "damaged socket or switch component", de: "beschädigte Steckdose oder beschädigter Schalter" },
        classification: { en: "visual electrical hypothesis", de: "visuelle Elektrohypothese" },
        supportingIndicators: { en: ["socket or switch damage is visually reported", "component cover or fixing condition may be impaired", "functional condition cannot be confirmed without electrical testing"], de: ["Schäden an Steckdose oder Schalter werden visuell berichtet", "Abdeckung oder Befestigung der Komponente kann beeinträchtigt sein", "die Funktionsfähigkeit kann ohne elektrische Prüfung nicht bestätigt werden"] },
        contradictingIndicators: { en: ["socket or switch is intact and securely fixed", "damage relates to adjacent finish only"], de: ["Steckdose oder Schalter ist intakt und sicher befestigt", "der Schaden betrifft nur angrenzende Oberflächen"] },
        requiredVerification: { en: ["Inspect the visible socket or switch cover without removing components.", "Document looseness, cracking, or missing parts.", "Qualified electrical testing may be appropriate before continued use decisions."], de: ["Sichtbare Steckdosen- oder Schalterabdeckung ohne Demontage prüfen.", "Lockerung, Risse oder fehlende Teile dokumentieren.", "Vor Entscheidungen zur weiteren Nutzung kann qualifizierte Elektroprüfung angemessen sein."] },
        potentialConsequences: { en: ["increased maintenance demand", "possible loss of service at the affected point", "further deterioration of the component"], de: ["erhöhter Instandhaltungsbedarf", "möglicher Nutzungsausfall am betroffenen Punkt", "weitere Verschlechterung der Komponente"] },
        recommendedActions: { en: ["Record the affected outlet or switch location.", "Avoid confirming internal failure from visible cover damage alone.", "Request qualified electrical follow-up where the component is loose or damaged."], de: ["Betroffene Steckdose oder Schalterlage erfassen.", "Aus sichtbarem Abdeckungsschaden allein kein internes Versagen bestätigen.", "Bei loser oder beschädigter Komponente qualifizierte Elektroprüfung veranlassen."] }
    },
    "unclear-or-missing-circuit-labeling": {
        cause: { en: "unclear or missing circuit labeling", de: "unklare oder fehlende Stromkreisbeschriftung" },
        label: { en: "unclear or missing circuit labeling", de: "unklare oder fehlende Stromkreisbeschriftung" },
        classification: { en: "documentation and operation hypothesis", de: "Dokumentations- und Betriebshypothese" },
        supportingIndicators: { en: ["circuit or distribution labeling is reported missing or unclear", "unclear labeling may affect maintenance and isolation procedures", "label accuracy cannot be confirmed without circuit tracing"], de: ["Stromkreis- oder Verteilungsbeschriftung wird als fehlend oder unklar berichtet", "unklare Beschriftung kann Wartung und Freischaltung beeinflussen", "die Richtigkeit der Beschriftung kann ohne Stromkreisverfolgung nicht bestätigt werden"] },
        contradictingIndicators: { en: ["labels are complete and verified against circuits", "label issue relates to non-electrical storage or signage"], de: ["Beschriftungen sind vollständig und gegen Stromkreise geprüft", "das Beschriftungsthema betrifft keine elektrische Lagerung oder Beschilderung"] },
        requiredVerification: { en: ["Review visible labels at the distribution board or consumer unit.", "Verify labels against documentation where available.", "Circuit identification should be confirmed by a qualified electrical specialist where needed."], de: ["Sichtbare Beschriftungen an Verteilung oder Sicherungskasten prüfen.", "Beschriftungen mit vorhandener Dokumentation abgleichen.", "Bei Bedarf sollte die Stromkreiszuordnung durch eine qualifizierte Elektrofachkraft bestätigt werden."] },
        potentialConsequences: { en: ["reduced maintainability", "longer fault isolation or maintenance time", "increased operational uncertainty"], de: ["verminderte Wartbarkeit", "längere Fehlersuche oder Wartungsdauer", "erhöhte betriebliche Unsicherheit"] },
        recommendedActions: { en: ["Document missing or unclear labels.", "Do not infer circuit function from labels alone.", "Recommend label verification only after qualified circuit identification."], de: ["Fehlende oder unklare Beschriftungen dokumentieren.", "Aus Beschriftungen allein keine Stromkreisfunktion ableiten.", "Beschriftungsprüfung erst nach qualifizierter Stromkreisidentifikation empfehlen."] }
    },
    "aged-or-visibly-deteriorated-electrical-components": {
        cause: { en: "aged or visibly deteriorated electrical components", de: "gealterte oder sichtbar verschlechterte Elektrokomponenten" },
        label: { en: "aged or visibly deteriorated electrical components", de: "gealterte oder sichtbar verschlechterte Elektrokomponenten" },
        classification: { en: "age-related visual hypothesis", de: "altersbezogene visuelle Hypothese" },
        supportingIndicators: { en: ["age or visible deterioration is reported in electrical components", "older visible components may require condition verification", "age alone is insufficient to confirm functional condition"], de: ["Alter oder sichtbare Verschlechterung wird an Elektrokomponenten berichtet", "ältere sichtbare Komponenten können Zustandsverifikation erfordern", "Alter allein reicht nicht aus, um die Funktionsfähigkeit zu bestätigen"] },
        contradictingIndicators: { en: ["older components are assessed as serviceable by qualified testing", "age metadata exists without observed deterioration"], de: ["ältere Komponenten werden durch qualifizierte Prüfung als gebrauchstauglich bewertet", "Altersmetadaten liegen ohne beobachtete Verschlechterung vor"] },
        requiredVerification: { en: ["Document visible age-related condition indicators.", "Review available maintenance or inspection records.", "Further electrical inspection may be appropriate before lifecycle or CAPEX conclusions."], de: ["Sichtbare altersbezogene Zustandsindikatoren dokumentieren.", "Vorhandene Wartungs- oder Prüfunterlagen prüfen.", "Vor Lebenszyklus- oder CAPEX-Schlüssen kann weitere Elektroprüfung angemessen sein."] },
        potentialConsequences: { en: ["future maintenance demand", "possible component deterioration", "increased need for condition-based planning"], de: ["künftiger Instandhaltungsbedarf", "mögliche Komponentenverschlechterung", "erhöhter Bedarf an zustandsbasierter Planung"] },
        recommendedActions: { en: ["Do not infer lifecycle action from age alone.", "Record only visible deterioration and available context.", "Use qualified assessment before lifecycle decisions."], de: ["Aus Alter allein keine Lebenszyklusmaßnahme ableiten.", "Nur sichtbare Verschlechterung und verfügbaren Kontext erfassen.", "Vor Lebenszyklusentscheidungen qualifizierte Bewertung nutzen."] }
    },
    "possible-overloaded-extension-or-adapter-arrangement": {
        cause: { en: "possible overloaded extension or adapter arrangement", de: "möglicherweise überlastete Verlängerungs- oder Adapteranordnung" },
        label: { en: "possible overloaded extension or adapter arrangement", de: "möglicherweise überlastete Verlängerungs- oder Adapteranordnung" },
        classification: { en: "visual electrical hypothesis", de: "visuelle Elektrohypothese" },
        supportingIndicators: { en: ["multiple extension leads or adapters are visibly concentrated", "arrangement may be associated with high plug load or temporary use", "actual circuit loading cannot be confirmed without testing"], de: ["mehrere Verlängerungsleitungen oder Adapter sind sichtbar konzentriert", "die Anordnung kann mit hoher Stecklast oder provisorischer Nutzung zusammenhängen", "die tatsächliche Stromkreisbelastung kann ohne Prüfung nicht bestätigt werden"] },
        contradictingIndicators: { en: ["extension arrangement is temporary and removed", "load assessment shows no concern under qualified testing"], de: ["die Verlängerungsanordnung ist temporär und entfernt", "eine Lastbewertung zeigt nach qualifizierter Prüfung keine Auffälligkeit"] },
        requiredVerification: { en: ["Document the visible adapter or extension arrangement.", "Do not infer circuit overload from plug count alone.", "Further electrical inspection may be appropriate where concentrated loads are observed."], de: ["Sichtbare Adapter- oder Verlängerungsanordnung dokumentieren.", "Aus der Anzahl der Stecker allein keine Stromkreisüberlastung ableiten.", "Bei konzentrierten Lasten kann weitere Elektroprüfung angemessen sein."] },
        potentialConsequences: { en: ["increased operational management need", "possible nuisance interruption", "increased maintenance attention for the affected area"], de: ["erhöhter betrieblicher Steuerungsbedarf", "mögliche störende Unterbrechung", "erhöhte Instandhaltungsaufmerksamkeit für den betroffenen Bereich"] },
        recommendedActions: { en: ["Record adapter type, location, and visible plug concentration.", "Avoid confirmed overload conclusions without electrical testing.", "Review whether permanent socket provision is adequate for observed use."], de: ["Adaptertyp, Lage und sichtbare Steckerkonzentration erfassen.", "Ohne elektrische Prüfung keine bestätigte Überlastung formulieren.", "Prüfen, ob dauerhafte Steckdosen für die beobachtete Nutzung ausreichen."] }
    },
    "visible-grounding-or-bonding-irregularity": {
        cause: { en: "visible grounding or bonding irregularity", de: "sichtbare Unregelmäßigkeit an Erdung oder Potentialausgleich" },
        label: { en: "visible grounding or bonding irregularity", de: "sichtbare Unregelmäßigkeit an Erdung oder Potentialausgleich" },
        classification: { en: "verification-required electrical hypothesis", de: "verifikationsbedürftige Elektrohypothese" },
        supportingIndicators: { en: ["grounding or bonding conductor condition is visibly irregular", "bonding continuity cannot be confirmed by visual inspection alone", "further electrical inspection may be appropriate"], de: ["Zustand von Erdungs- oder Potentialausgleichsleiter erscheint sichtbar unregelmäßig", "Potentialausgleichskontinuität kann durch Sichtprüfung allein nicht bestätigt werden", "weitere Elektroprüfung kann angemessen sein"] },
        contradictingIndicators: { en: ["bonding conductor is intact and verified by qualified testing", "reported conductor is unrelated to grounding or bonding"], de: ["Potentialausgleichsleiter ist intakt und durch qualifizierte Prüfung verifiziert", "der berichtete Leiter steht nicht mit Erdung oder Potentialausgleich in Zusammenhang"] },
        requiredVerification: { en: ["Document visible grounding or bonding conductor condition.", "Do not test or manipulate conductors during visual inspection.", "Qualified electrical testing is required before confirming continuity or function."], de: ["Sichtbaren Zustand von Erdungs- oder Potentialausgleichsleitern dokumentieren.", "Leiter während der Sichtprüfung nicht prüfen oder manipulieren.", "Vor Bestätigung von Kontinuität oder Funktion ist qualifizierte Elektroprüfung erforderlich."] },
        potentialConsequences: { en: ["increased need for specialist verification", "possible operational uncertainty for protective measures", "maintenance follow-up requirement"], de: ["erhöhter Bedarf an fachlicher Verifikation", "mögliche betriebliche Unsicherheit bei Schutzmaßnahmen", "erforderliche Instandhaltungsnachverfolgung"] },
        recommendedActions: { en: ["Record the visible conductor and connection context.", "Avoid confirming loss of grounding or bonding from visual observation alone.", "Escalate to qualified electrical assessment where a conductor appears loose, missing, or damaged."], de: ["Sichtbaren Leiter- und Anschlusskontext erfassen.", "Aus Sichtbeobachtung allein keinen Verlust von Erdung oder Potentialausgleich bestätigen.", "Bei lose, fehlend oder beschädigt erscheinendem Leiter qualifizierte Elektroprüfung veranlassen."] }
    }
});

export default electricalSystemsBilingualResources;

function freezeResources(resources) {
    Object.values(resources).forEach((resource) => {
        Object.values(resource).forEach((field) => {
            Object.values(field).forEach((value) => {
                if (Array.isArray(value)) {
                    Object.freeze(value);
                }
            });
            Object.freeze(field);
        });
        Object.freeze(resource);
    });

    return Object.freeze(resources);
}