const sanitarySystemsBilingualResources = freezeResources({
    "visible-leakage-at-sanitary-component": {
        cause: { en: "visible leakage around sanitary component", de: "sichtbare Leckage an einer Sanitärkomponente" },
        label: { en: "visible leakage around sanitary component", de: "sichtbare Leckage an einer Sanitärkomponente" },
        classification: { en: "visual sanitary hypothesis", de: "visuelle Sanitärhypothese" },
        supportingIndicators: { en: ["visible leakage is reported at or near a sanitary component", "water escape may indicate a local joint, fitting, or component condition", "visual inspection alone cannot confirm the internal cause"], de: ["sichtbare Leckage wird an oder nahe einer Sanitärkomponente berichtet", "Wasseraustritt kann auf einen lokalen Anschluss-, Armatur- oder Bauteilzustand hinweisen", "die Sichtprüfung allein kann die innere Ursache nicht bestätigen"] },
        contradictingIndicators: { en: ["reported water is confirmed to originate from a non-sanitary source", "component is dry during follow-up review"], de: ["das berichtete Wasser stammt nach Prüfung aus einer nicht sanitären Quelle", "die Komponente ist bei der Nachprüfung trocken"] },
        requiredVerification: { en: ["Document the affected component, location, and visible moisture extent.", "Further inspection may be appropriate before assigning cause.", "Avoid opening concealed sanitary components during visual review."], de: ["Betroffene Komponente, Lage und sichtbare Feuchteausdehnung dokumentieren.", "Vor einer Ursachenzuordnung kann eine weiterführende Prüfung angemessen sein.", "Verdeckte Sanitärkomponenten im Rahmen der Sichtprüfung nicht öffnen."] },
        potentialConsequences: { en: ["possible local deterioration of adjacent finishes", "increased maintenance attention", "possible interruption of fixture use if the condition progresses"], de: ["mögliche lokale Verschlechterung angrenzender Oberflächen", "erhöhter Instandhaltungsbedarf", "mögliche Einschränkung der Nutzung der Armatur oder des Sanitärobjekts bei Fortschreiten"] },
        recommendedActions: { en: ["Record visible leakage without treating it as pipe failure.", "Keep conclusions within visual-inspection limits.", "Request qualified sanitary review where leakage remains unexplained."], de: ["Sichtbare Leckage erfassen, ohne sie als Rohrversagen zu behandeln.", "Schlussfolgerungen auf die Grenzen der Sichtprüfung beschränken.", "Bei ungeklärter Leckage qualifizierte Sanitärprüfung veranlassen."] }
    },
    "visible-corrosion-staining-or-moisture": {
        cause: { en: "visible corrosion, staining, or moisture around sanitary components", de: "sichtbare Korrosion, Verfärbung oder Feuchte an Sanitärkomponenten" },
        label: { en: "visible corrosion, staining, or moisture around sanitary components", de: "sichtbare Korrosion, Verfärbung oder Feuchte an Sanitärkomponenten" },
        classification: { en: "visual sanitary hypothesis", de: "visuelle Sanitärhypothese" },
        supportingIndicators: { en: ["corrosion, staining, or moisture is visually observed near sanitary components", "surface condition may indicate repeated wetting or local deterioration", "visual inspection alone cannot confirm source or progression"], de: ["Korrosion, Verfärbung oder Feuchte wird nahe Sanitärkomponenten visuell beobachtet", "der Oberflächenzustand kann auf wiederholte Befeuchtung oder lokale Verschlechterung hinweisen", "die Sichtprüfung allein kann Quelle oder Verlauf nicht bestätigen"] },
        contradictingIndicators: { en: ["staining is confirmed to be unrelated surface contamination", "sanitary components are dry and visually intact at follow-up"], de: ["die Verfärbung erweist sich als unabhängige Oberflächenverunreinigung", "Sanitärkomponenten sind bei der Nachprüfung trocken und visuell intakt"] },
        requiredVerification: { en: ["Document staining, corrosion, and moisture proximity with location context.", "Check adjacent visible sanitary components for related evidence.", "Further inspection may be appropriate where moisture and sanitary components coincide."], de: ["Verfärbung, Korrosion und Feuchtenähe mit Lagebezug dokumentieren.", "Angrenzende sichtbare Sanitärkomponenten auf zusammenhängende Hinweise prüfen.", "Bei Zusammentreffen von Feuchte und Sanitärkomponenten kann weitere Prüfung angemessen sein."] },
        potentialConsequences: { en: ["possible deterioration of adjacent materials", "increased maintenance demand", "possible concealed moisture extension if unresolved"], de: ["mögliche Verschlechterung angrenzender Materialien", "erhöhter Instandhaltungsbedarf", "mögliche verdeckte Feuchteausbreitung bei ausbleibender Klärung"] },
        recommendedActions: { en: ["Record visible staining and moisture relationship to sanitary components.", "Avoid attributing concealed failure from staining alone.", "Coordinate moisture-source review where sanitary components are adjacent."], de: ["Sichtbare Verfärbung und Feuchtebezug zu Sanitärkomponenten erfassen.", "Aus Verfärbung allein kein verdecktes Versagen ableiten.", "Bei angrenzenden Sanitärkomponenten Prüfung der Feuchtequelle koordinieren."] }
    },
    "damaged-or-loose-sanitary-fixture": {
        cause: { en: "damaged or loose sanitary fixture", de: "beschädigtes oder loses Sanitärobjekt" },
        label: { en: "damaged or loose sanitary fixture", de: "beschädigtes oder loses Sanitärobjekt" },
        classification: { en: "visual sanitary hypothesis", de: "visuelle Sanitärhypothese" },
        supportingIndicators: { en: ["fixture damage or looseness is visually reported", "fixture condition may affect serviceability or adjacent seals", "functional condition cannot be confirmed from appearance alone"], de: ["Beschädigung oder Lockerung eines Sanitärobjekts wird visuell berichtet", "der Zustand kann Nutzbarkeit oder angrenzende Dichtungen beeinflussen", "die Funktionsfähigkeit kann aus dem Erscheinungsbild allein nicht bestätigt werden"] },
        contradictingIndicators: { en: ["fixture is intact and securely fixed", "reported damage relates to adjacent finish only"], de: ["das Sanitärobjekt ist intakt und fest montiert", "der gemeldete Schaden betrifft nur angrenzende Oberflächen"] },
        requiredVerification: { en: ["Inspect visible fixture surfaces and accessible fixings without dismantling.", "Document cracks, looseness, or damaged visible parts.", "Further sanitary inspection may be appropriate before defining scope."], de: ["Sichtbare Oberflächen und zugängliche Befestigungen ohne Demontage prüfen.", "Risse, Lockerung oder beschädigte sichtbare Teile dokumentieren.", "Vor Festlegung des Umfangs kann weitere Sanitärprüfung angemessen sein."] },
        potentialConsequences: { en: ["increased maintenance demand", "possible localized leakage at fixture interfaces", "possible temporary limitation of fixture use"], de: ["erhöhter Instandhaltungsbedarf", "mögliche lokale Leckage an Objektanschlüssen", "mögliche zeitweise Nutzungseinschränkung des Sanitärobjekts"] },
        recommendedActions: { en: ["Record the affected fixture and visible condition.", "Do not infer concealed connection failure from fixture damage alone.", "Request qualified follow-up where fixture movement or damage is observed."], de: ["Betroffenes Sanitärobjekt und sichtbaren Zustand erfassen.", "Aus Objektschaden allein kein verdecktes Anschlussversagen ableiten.", "Bei Bewegung oder Beschädigung qualifizierte Nachprüfung veranlassen."] }
    },
    "possible-drainage-restriction-indicator": {
        cause: { en: "possible drainage restriction indicator", de: "möglicher Hinweis auf Ablaufbehinderung" },
        label: { en: "possible drainage restriction indicator", de: "möglicher Hinweis auf Ablaufbehinderung" },
        classification: { en: "visual and operational sanitary hypothesis", de: "visuelle und betriebliche Sanitärhypothese" },
        supportingIndicators: { en: ["blocked or slow drainage is reported at a sanitary fixture or drain", "observable drainage behavior may indicate a local restriction", "visual inspection alone cannot confirm blockage location or cause"], de: ["verstopfter oder langsamer Ablauf wird an Sanitärobjekt oder Ablauf berichtet", "beobachtbares Ablaufverhalten kann auf eine lokale Behinderung hinweisen", "die Sichtprüfung allein kann Lage oder Ursache einer Blockade nicht bestätigen"] },
        contradictingIndicators: { en: ["drainage is observed as normal during follow-up", "reported condition is confirmed to be unrelated to sanitary drainage"], de: ["der Ablauf zeigt sich bei der Nachprüfung unauffällig", "der berichtete Zustand steht nicht mit der Sanitärentwässerung in Zusammenhang"] },
        requiredVerification: { en: ["Document the affected fixture or drain and observed drainage behavior.", "Further inspection may be appropriate before locating a restriction.", "Avoid concluding concealed pipe condition without additional evidence."], de: ["Betroffenes Sanitärobjekt oder Ablauf und beobachtetes Ablaufverhalten dokumentieren.", "Vor Lokalisierung einer Behinderung kann weitere Prüfung angemessen sein.", "Ohne zusätzliche Hinweise keine verdeckte Rohrleitungsbeschaffenheit ableiten."] },
        potentialConsequences: { en: ["possible reduced fixture usability", "increased maintenance attention", "possible local overflow if drainage worsens"], de: ["mögliche verringerte Nutzbarkeit des Sanitärobjekts", "erhöhter Instandhaltungsbedarf", "möglicher lokaler Überlauf bei Verschlechterung des Ablaufs"] },
        recommendedActions: { en: ["Describe the observed drainage symptom without confirming blockage.", "Keep findings separate from CCTV or pressure-test conclusions.", "Request sanitary specialist review where symptoms persist."], de: ["Beobachtetes Ablaufanzeichen beschreiben, ohne eine Blockade zu bestätigen.", "Feststellungen von Kamera- oder Druckprüfergebnissen trennen.", "Bei fortbestehenden Anzeichen Sanitärfachprüfung veranlassen."] }
    },
    "unpleasant-odour-near-sanitary-drainage": {
        cause: { en: "unpleasant odour near sanitary drainage component", de: "unangenehmer Geruch nahe einer Sanitärentwässerung" },
        label: { en: "unpleasant odour near sanitary drainage component", de: "unangenehmer Geruch nahe einer Sanitärentwässerung" },
        classification: { en: "visual and sensory sanitary hypothesis", de: "visuelle und sensorische Sanitärhypothese" },
        supportingIndicators: { en: ["odour is reported near a drain, trap, or sanitary fixture", "odour may indicate a trap, vent, or drainage condition requiring verification", "visual inspection alone cannot confirm internal drainage cause"], de: ["Geruch wird nahe Ablauf, Geruchsverschluss oder Sanitärobjekt berichtet", "Geruch kann auf einen zu prüfenden Zustand von Geruchsverschluss, Lüftung oder Entwässerung hinweisen", "die Sichtprüfung allein kann eine innere Entwässerungsursache nicht bestätigen"] },
        contradictingIndicators: { en: ["odour is absent during follow-up", "odour source is confirmed unrelated to sanitary drainage"], de: ["bei der Nachprüfung ist kein Geruch vorhanden", "die Geruchsquelle steht nicht mit der Sanitärentwässerung in Zusammenhang"] },
        requiredVerification: { en: ["Record the location and sanitary component near the odour report.", "Check visible trap, drain, and fixture context where accessible.", "Further inspection may be appropriate before assigning cause."], de: ["Lage und Sanitärkomponente nahe der Geruchsmeldung erfassen.", "Sichtbaren Geruchsverschluss-, Ablauf- und Objektkontext soweit zugänglich prüfen.", "Vor Ursachenannahme kann weitere Prüfung angemessen sein."] },
        potentialConsequences: { en: ["possible occupant nuisance", "increased maintenance attention", "possible need for fixture or trap review"], de: ["mögliche Nutzerbeeinträchtigung", "erhöhter Instandhaltungsbedarf", "möglicher Prüfbedarf an Objekt oder Geruchsverschluss"] },
        recommendedActions: { en: ["Report odour as an observed condition, not a confirmed drainage defect.", "Avoid indoor air or contamination conclusions without testing.", "Request follow-up where odour persists near sanitary components."], de: ["Geruch als beobachteten Zustand berichten, nicht als bestätigten Entwässerungsdefekt.", "Ohne Prüfung keine Innenraumluft- oder Kontaminationsschlüsse ziehen.", "Bei fortbestehendem Geruch nahe Sanitärkomponenten Nachprüfung veranlassen."] }
    },
    "missing-or-damaged-sanitary-seal": {
        cause: { en: "missing or damaged sanitary seal", de: "fehlende oder beschädigte Sanitärdichtung" },
        label: { en: "missing or damaged sanitary seal", de: "fehlende oder beschädigte Sanitärdichtung" },
        classification: { en: "visual sanitary hypothesis", de: "visuelle Sanitärhypothese" },
        supportingIndicators: { en: ["seal condition is reported missing, damaged, or discontinuous", "seal condition may affect splash water control or odour separation", "visual inspection alone cannot confirm concealed connection condition"], de: ["Dichtungszustand wird als fehlend, beschädigt oder unterbrochen berichtet", "der Dichtungszustand kann Spritzwasserschutz oder Geruchstrennung beeinflussen", "die Sichtprüfung allein kann den verdeckten Anschlusszustand nicht bestätigen"] },
        contradictingIndicators: { en: ["seal is continuous and intact", "reported gap is unrelated to sanitary fixture or connection"], de: ["die Dichtung ist durchgehend und intakt", "die gemeldete Fuge steht nicht mit Sanitärobjekt oder Anschluss in Zusammenhang"] },
        requiredVerification: { en: ["Document the affected seal, connection, or fixture interface.", "Check visible adjacent staining or moisture where accessible.", "Further sanitary inspection may be appropriate before defining repair scope."], de: ["Betroffene Dichtung, Anschluss- oder Objektfuge dokumentieren.", "Sichtbare angrenzende Verfärbung oder Feuchte soweit zugänglich prüfen.", "Vor Festlegung eines Reparaturumfangs kann weitere Sanitärprüfung angemessen sein."] },
        potentialConsequences: { en: ["possible local moisture exposure", "increased maintenance need", "possible odour or splash-water nuisance"], de: ["mögliche lokale Feuchtebeanspruchung", "erhöhter Instandhaltungsbedarf", "mögliche Geruchs- oder Spritzwasserbeeinträchtigung"] },
        recommendedActions: { en: ["Record visible seal condition without inferring concealed failure.", "Avoid compliance or replacement conclusions from visual seal condition alone.", "Request qualified follow-up where seal discontinuity is associated with moisture."], de: ["Sichtbaren Dichtungszustand erfassen, ohne verdecktes Versagen abzuleiten.", "Aus sichtbarem Dichtungszustand allein keine Konformitäts- oder Austauschschlüsse ziehen.", "Bei Dichtungsunterbrechung mit Feuchtebezug qualifizierte Nachprüfung veranlassen."] }
    },
    "possible-backflow-indication": {
        cause: { en: "possible backflow indication at sanitary drain", de: "mögliches Rückstauanzeichen am Sanitärablauf" },
        label: { en: "possible backflow indication at sanitary drain", de: "mögliches Rückstauanzeichen am Sanitärablauf" },
        classification: { en: "visual and operational sanitary hypothesis", de: "visuelle und betriebliche Sanitärhypothese" },
        supportingIndicators: { en: ["backflow-like behavior is reported at a sanitary drain or fixture", "observed reverse flow may indicate a drainage or surcharge condition", "visual inspection alone cannot confirm system cause or extent"], de: ["rückstauähnliches Verhalten wird an Sanitärablauf oder Sanitärobjekt berichtet", "beobachteter Rückfluss kann auf einen Entwässerungs- oder Überlastungszustand hinweisen", "die Sichtprüfung allein kann Systemursache oder Ausmaß nicht bestätigen"] },
        contradictingIndicators: { en: ["no reverse flow is observed during follow-up", "condition is confirmed to originate outside the sanitary system"], de: ["bei der Nachprüfung wird kein Rückfluss beobachtet", "der Zustand hat seinen Ursprung außerhalb des Sanitärsystems"] },
        requiredVerification: { en: ["Document the affected drain or fixture and observed direction of water movement.", "Review whether the condition is local or repeated where information is available.", "Further sanitary inspection may be appropriate before assigning cause."], de: ["Betroffenen Ablauf oder Sanitärobjekt und beobachtete Wasserbewegungsrichtung dokumentieren.", "Soweit Informationen vorliegen prüfen, ob der Zustand lokal oder wiederkehrend ist.", "Vor Ursachenannahme kann weitere Sanitärprüfung angemessen sein."] },
        potentialConsequences: { en: ["possible temporary loss of fixture use", "increased hygiene-related maintenance attention", "possible local water damage if repeated"], de: ["möglicher zeitweiser Nutzungsausfall des Sanitärobjekts", "erhöhter hygienebezogener Instandhaltungsbedarf", "mögliche lokale Wasserschäden bei Wiederholung"] },
        recommendedActions: { en: ["Use possible backflow wording only where observable behavior is reported.", "Do not confirm blockage or system failure from visual evidence alone.", "Request qualified review where reverse flow is observed."], de: ["Rückstau nur als mögliches Anzeichen formulieren, wenn beobachtbares Verhalten berichtet wird.", "Aus visuellen Hinweisen allein keine Blockade oder Systemstörung bestätigen.", "Bei beobachtetem Rückfluss qualifizierte Prüfung veranlassen."] }
    },
    "poor-support-or-protection-of-sanitary-pipework": {
        cause: { en: "poor support or protection of sanitary pipework", de: "unzureichende Befestigung oder Schutz der Sanitärrohrleitung" },
        label: { en: "poor support or protection of sanitary pipework", de: "unzureichende Befestigung oder Schutz der Sanitärrohrleitung" },
        classification: { en: "visual sanitary hypothesis", de: "visuelle Sanitärhypothese" },
        supportingIndicators: { en: ["pipe support or insulation condition is visually irregular", "poor support or protection may affect durability or alignment", "installation adequacy cannot be confirmed from visual inspection alone"], de: ["Rohrhalterung oder Dämmzustand erscheint visuell unregelmäßig", "unzureichende Befestigung oder Schutz kann Dauerhaftigkeit oder Ausrichtung beeinflussen", "die Angemessenheit der Installation kann aus der Sichtprüfung allein nicht bestätigt werden"] },
        contradictingIndicators: { en: ["pipework is adequately supported and protected", "reported support relates to non-sanitary services"], de: ["die Rohrleitung ist ausreichend befestigt und geschützt", "der gemeldete Halterungszustand betrifft keine Sanitärleitung"] },
        requiredVerification: { en: ["Document visible pipe support, sagging, or insulation condition.", "Review accessible pipe route and support context without dismantling.", "Further inspection may be appropriate before classifying installation quality."], de: ["Sichtbare Rohrhalterung, Durchhängung oder Dämmzustand dokumentieren.", "Zugänglichen Leitungsverlauf und Halterungskontext ohne Demontage prüfen.", "Vor Einstufung der Installationsqualität kann weitere Prüfung angemessen sein."] },
        potentialConsequences: { en: ["possible increased maintenance demand", "possible local movement of pipework", "possible deterioration of visible insulation or supports"], de: ["möglicherweise erhöhter Instandhaltungsbedarf", "mögliche lokale Bewegung der Rohrleitung", "mögliche Verschlechterung sichtbarer Dämmung oder Halterungen"] },
        recommendedActions: { en: ["Record visible support or protection irregularities.", "Do not infer code compliance from visual support condition alone.", "Request qualified sanitary review if service pipework appears unsupported."], de: ["Sichtbare Unregelmäßigkeiten an Befestigung oder Schutz erfassen.", "Aus sichtbarem Halterungszustand allein keine Regelkonformität ableiten.", "Bei unzureichend befestigt erscheinenden Leitungen qualifizierte Sanitärprüfung veranlassen."] }
    },
    "visible-deterioration-at-sanitary-connection": {
        cause: { en: "visible deterioration at sanitary connection", de: "sichtbare Verschlechterung an einem Sanitäranschluss" },
        label: { en: "visible deterioration at sanitary connection", de: "sichtbare Verschlechterung an einem Sanitäranschluss" },
        classification: { en: "visual sanitary hypothesis", de: "visuelle Sanitärhypothese" },
        supportingIndicators: { en: ["connection, valve, or fitting deterioration is visually reported", "visible deterioration may indicate increased maintenance need", "visual inspection alone cannot confirm internal service condition"], de: ["Verschlechterung an Anschluss, Ventil oder Fitting wird visuell berichtet", "sichtbare Verschlechterung kann auf erhöhten Instandhaltungsbedarf hinweisen", "die Sichtprüfung allein kann den inneren Funktionszustand nicht bestätigen"] },
        contradictingIndicators: { en: ["connection and fitting are intact during follow-up", "reported deterioration is unrelated to sanitary services"], de: ["Anschluss und Fitting sind bei der Nachprüfung intakt", "die gemeldete Verschlechterung steht nicht mit Sanitärinstallationen in Zusammenhang"] },
        requiredVerification: { en: ["Document the affected connection, valve, or fitting.", "Check for visible moisture, staining, or movement where accessible.", "Further sanitary inspection may be appropriate before lifecycle conclusions."], de: ["Betroffenen Anschluss, Ventil oder Fitting dokumentieren.", "Sichtbare Feuchte, Verfärbung oder Bewegung soweit zugänglich prüfen.", "Vor Lebenszyklus- oder Maßnahmenannahmen kann weitere Sanitärprüfung angemessen sein."] },
        potentialConsequences: { en: ["possible localized leakage if deterioration progresses", "increased maintenance demand", "possible service interruption during future works"], de: ["mögliche lokale Leckage bei fortschreitender Verschlechterung", "erhöhter Instandhaltungsbedarf", "mögliche Nutzungsunterbrechung bei späteren Arbeiten"] },
        recommendedActions: { en: ["Record visible connection condition without treating it as pipe failure.", "Avoid mandated lifecycle action wording from visual deterioration alone.", "Use qualified assessment before lifecycle decisions."], de: ["Sichtbaren Anschlusszustand erfassen, ohne ihn als Rohrversagen zu behandeln.", "Aus sichtbarer Verschlechterung allein keine verpflichtende Lebenszyklusmaßnahme ableiten.", "Vor Lebenszyklusentscheidungen qualifizierte Beurteilung nutzen."] }
    }
});

export default sanitarySystemsBilingualResources;

function freezeResources(resources) {
    Object.values(resources).forEach((resource) => {
        Object.values(resource).forEach((field) => {
            Object.values(field).forEach((value) => {
                if (Array.isArray(value)) {
                    Object.freeze(value);
                }
            });
            Object.freeze(field);
        });
        Object.freeze(resource);
    });

    return Object.freeze(resources);
}